version: '2.1'

services:
  db:
    image: postgres:13.4
    environment:
      - POSTGRES_DB=houses
      - POSTGRES_USER=hombre
      - POSTGRES_PASSWORD=heslo1234
    ports:
      - "5599:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: {}
  